## Import NumPy
NumPy is usually imported under the np alias.

In [1]:
import numpy as np

In [2]:
y=np.array([1,2,3,4,5,6])
y

array([1, 2, 3, 4, 5, 6])

we can create list tuple in numpy

***properties***

1.numpy is a library used for working with arrays

2.to create a "n"-dimenstional array of object

3.which gives tools ,by which we can manipulate ***N-dimenstions array***

Array:collection of similar type of "data"

it can held n number of data
n=0 it is called scalar
n=1 it is called vector 

default it will be column vector 




***important array properties***

definition : gives output in less time when comparied to python .

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

1.homogeneous array :array accpects only same or similar type of data

2.They are mutable:we can edit,replace,delect and insert

3.they are ordered because of index value 

***What’s the difference between a Python list and a NumPy array?***

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

***Create a NumPy ndarray Object***

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [6]:
import numpy as ly
m=ly.array([1,2,3])
type(m)

numpy.ndarray

Dimenstions in array 


### 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array

In [7]:
import numpy as pi
k=pi.array([45])
k

array([45])

### Check Number of Dimensions?
NumPy Arrays provides the **ndim** attribute that returns an integer that tells us how many dimensions the array have.

In [14]:
import numpy as pi
k=pi.array(45)
k.ndim

0

1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.


In [15]:
l=pi.array(([1,2,3]))
l.ndim


1

2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

In [26]:
import numpy as kd
hi=kd.array([[1,2,3],[4,5,6]])
hi.ndim


2

3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [27]:
import numpy as d3
v=d3.array([[[1,23,25,28],[63,78,87,77]]])
v.ndim

3

### Higher Dimensional Arrays to create an higer dimenstion array..with the help of ndim

In [30]:
import numpy as ly
k=ly.array([1,2,3,4,5,6],ndmin=5)

array([[[[[1, 2, 3, 4, 5, 6]]]]])

# zero functions

In [89]:
ly.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
ly.ones([16])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
ly.empty([9])

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 8.45840386e-321, 3.11525958e-307, 1.24610723e-306,
       0.00000000e+000])

# range function in numpy

In [50]:
import numpy as sprit
b=sprit.arange(5)
b

array([0, 1, 2, 3, 4])

#### range function for skiping accounding to given skip number

In [53]:
k=sprit.arange(1,22)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [56]:
m=sprit.arange(1,22,2)
m

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

 ## NumPy Array Indexing
 one-dimenstion
 


In [108]:
import numpy as jup
hope=jup.arange(2,165,13)
print(hope)
print(hope[5])

[  2  15  28  41  54  67  80  93 106 119 132 145 158]
67


In [109]:
min=jup.array([1,2,3,4,5,6,7,8,9,10])
print(min[4])


5


In [110]:
print(min[4]+min[6])

12



### To access elements from 2-D arrays
we can use comma separated integers representing the dimension and the index of the element.


In [111]:
import numpy as ki
h=ki.array([[1,2,3,4],[4,5,6,7]])
print(h)
print(h.ndim)

[[1 2 3 4]
 [4 5 6 7]]
2


In [112]:
print("accesing the third element in 2 row ==:",h[1,2])

accesing the third element in 2 row ==: 6


### Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element

In [120]:
z=ki.array([[[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]]])
print(z.ndim)
z[0,2,2]
z

3


array([[[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [121]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[1,1,1]

11

# LINE SPACE 
it is used to print the number of elements required as per user if we gave arange(1,20) we can print 5 or 6 elements

In [69]:
import numpy as ut
line=ut.linspace(1,20,num=3)
print(line)


[ 1.  10.5 20. ]


# shape of array

In [79]:
import numpy as op
f=op.array([[1,2,3,4,5],[6,7,8,9,10]])
f.shape

(2, 5)

In [80]:
g=op.array([1,2,3,6])
g.shape
#in single dimenstions the shape gives the number of elements in the n-dimenstion array

(4,)

In [86]:
u=op.array([1,2,3,4],ndmin=5)
print(u.ndim)
print(u.shape)

5
(1, 1, 1, 1, 4)


In [87]:
u

array([[[[[1, 2, 3, 4]]]]])

# full method 
full it fills all the element with only given value

In [122]:
import numpy as ful

In [123]:
r=ful.full((4,6),69)
r

array([[69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69]])

# eye method
which will fill the diagnol in the matrix

In [97]:
p=ful.eye(8)
p

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### Slicing arrays:

***licing in python means taking elements from one given index to another given index.***

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [124]:
import numpy as ike
hi=ike.array([1,2,3,4,5,6,])
hi[0:3]

array([1, 2, 3])

### Negative Slicing
Use the minus operator to refer to an index from the end:

In [125]:
ko=ike.array([1,5,6,7,8,9,10,11,12,13,14])
ko[-3:-1]

array([12, 13])

# step in slicing 

In [2]:
import numpy as li
y=li.array([1,2,3,4,5,7,9,5,10])
y[1: :2]

array([2, 4, 7, 5])

### Slicing 2-D Arrays
Example
From the second element, slice elements from index 1 to index 4 (not included):

In [17]:
sms=li.array([[1,2,3,4],[5,6,7,8]])
print(sms.ndim)
sms[1,1:2]
print(sms.shape)
print(sms)

2
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [18]:
sms[1,0:3]

array([5, 6, 7])

In [19]:
# to get 3 number from array
print(sms[0,2:3])

[3]


In [27]:
#if we want to return both the elements in two different ...
print(sms[0:2,2])

[3 7]


In [6]:
#step slicing in array
import numpy as dk
arr=dk.array([10, 15, 20, 25, 30, 35, 40])
arr[0: :2]




array([10, 20, 30, 40])

Data Types in Python

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


 ### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )


 ###  Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [7]:
import numpy as kl
c=kl.array([1,2,5,6,7,8])
c.dtype

dtype('int32')

In [29]:
m=kl.array([1,2,3,4,5],ndmin=3,dtype=float)
print(m)


[[[1. 2. 3. 4. 5.]]]


### Converting Data Type on Existing Arrays

In [8]:
k=kl.array([1,2,3,4,5,6],dtype="f")
k

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [9]:
print(k)

[1. 2. 3. 4. 5. 6.]


Get the ***Shape*** of an Array

In [10]:
import numpy as we
s=we.array([[1,2,3,4,5],[6,7,8,9,10]])
print(s.ndim)
s.shape
print(s)
print(s[1,3])
#slicing
print(s[1,0:5])

2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9
[ 6  7  8  9 10]


2=rows and 5=columns 

In [11]:
h=we.array([1,2,3,4,5],ndmin=3)
print(h)
print(h.shape)

[[[1 2 3 4 5]]]
(1, 1, 5)


# Reshape

In [55]:
import numpy as shel
d=shel.array([[1,2,3,4,5,6,7,8],[23,24,25,26,27,28,29,30]])
k=d.reshape(4,4)
print(k)
k[2,2]



[[ 1  2  3  4]
 [ 5  6  7  8]
 [23 24 25 26]
 [27 28 29 30]]


25

In [39]:
import numpy as hi
g=hi.array([1,2,3,4,5,6,7,8])
g.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [64]:
#coding on reshape 
import numpy as alpha
m=alpha.arange(1,21)
k=m.reshape(5,4)
print(m.shape)
print(m.ndim)
print(k[3,2])



(20,)
1
15


we can to +,-,,/,// it will accces element wise and while adding and sub the shape should be matched between two arrays*

we can also use comparison operator =,<,>,!

In [66]:
print(k)
print(k+2)
k*2
k[(k%2==0)]




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [68]:
k[(k%2==0) & (k%5==0)]

array([10, 20])